version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go
    versions:
    - 1.37.0
    - 1.37.1
    - 1.37.10
    - 1.37.11
    - 1.37.12
    - 1.37.13
    - 1.37.14
    - 1.37.15
    - 1.37.16
    - 1.37.17
    - 1.37.18
    - 1.37.19
    - 1.37.2
    - 1.37.20
    - 1.37.21
    - 1.37.22
    - 1.37.23
    - 1.37.24
    - 1.37.25
    - 1.37.26
    - 1.37.27
    - 1.37.28
    - 1.37.29
    - 1.37.3
    - 1.37.30
    - 1.37.31
    - 1.37.32
    - 1.37.33
    - 1.37.5
    - 1.37.6
    - 1.37.7
    - 1.37.8
    - 1.37.9
    - 1.38.0
    - 1.38.1
    - 1.38.11
    - 1.38.13
    - 1.38.14
    - 1.38.15
    - 1.38.16
    - 1.38.17
    - 1.38.18
    - 1.38.19
    - 1.38.2
    - 1.38.20
    - 1.38.21
    - 1.38.22
    - 1.38.23
    - 1.38.24
    - 1.38.25
    - 1.38.26
    - 1.38.3
    - 1.38.4
    - 1.38.6
    - 1.38.7
    - 1.38.8
    - 1.38.9
  - dependency-name: cloud.google.com/go/pubsub
    versions:
    - 1.10.0
    - 1.10.1
    - 1.10.2
    - 1.9.1
  - dependency-name: google.golang.org/api
    versions:
    - 0.37.0
    - 0.38.0
    - 0.39.0
    - 0.40.0
    - 0.41.0
    - 0.42.0
    - 0.43.0
    - 0.44.0
  - dependency-name: google.golang.org/grpc
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
  - dependency-name: cloud.google.com/go
    versions:
    - 0.75.0
    - 0.76.0
    - 0.77.0
    - 0.78.0
    - 0.79.0
    - 0.80.0
  - dependency-name: go.opencensus.io
    versions:
    - 0.22.5
    - 0.22.6
  - dependency-name: github.com/google/go-cmp
    versions:
    - 0.5.4
  - dependency-name: github.com/Shopify/sarama
    versions:
    - 1.27.2
